# Generated by Django 5.2.1 on 2025-05-16 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='PO number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('ORDERED', 'Ordered'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='status')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='order date')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='expected delivery date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='tax')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='shipping cost')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discount')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('supplier_reference', models.CharField(blank=True, max_length=100, verbose_name='supplier reference')),
            ],
            options={
                'verbose_name': 'purchase order',
                'verbose_name_plural': 'purchase orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField(verbose_name='quantity ordered')),
                ('quantity_received', models.PositiveIntegerField(default=0, verbose_name='quantity received')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='unit price')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='line total')),
            ],
            options={
                'verbose_name': 'purchase order item',
                'verbose_name_plural': 'purchase order items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_date', models.DateField(default=django.utils.timezone.now, verbose_name='receive date')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'purchase order receive',
                'verbose_name_plural': 'purchase order receives',
                'ordering': ['-receive_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderReceiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity received')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'receive item',
                'verbose_name_plural': 'receive items',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='tax ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary contact')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'supplier contact',
                'verbose_name_plural': 'supplier contacts',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
